apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo1
    memo: demo1
  name: demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  strategy: {}
  template:
    metadata:
      labels:
        app: demo1
      annotations:
        dapr.io/enabled: "false"
        dapr.io/app-id: demo1
    spec:
      containers:
      - image: sample/dynamodb:latest
        name: demo1
        ports:
        - containerPort: 8080
status: {}